import { themes } from "../../themes";

/**
 * Validates the the margin is correct, returning true if so
 * @param  {number} value     The value for the margin
 * @param  {String} side      The side of the margin we are checking [top, left, bottom, right]
 * @return {Boolean}          True if the margin is valid, false otherwise
 */
const validateMargin = (value, side) => {
    if (value === null || value === undefined) {
        console.warn(`W005 - The ${side} of the margin was not specified and is required`);
        return false;
    }

    return true;
};

/**
 * Sets the dimensions in the Redux store
 * @param  {Number} width   The width of the chart
 * @param  {Number} height  The height of the chart
 * @param  {Object} margin  The margin for the chart
 * @return {Object}         A redux action object
 */
const setDimensions = (width, height, margin) => {
    if (!margin) {
        console.warn("W004 - A margin was not provided but is required");
        return;
    }

    // prettier-ignore
    if (!validateMargin(margin.left, "left") || 
        !validateMargin(margin.top, "top") ||
        !validateMargin(margin.bottom, "bottom") ||
        !validateMargin(margin.right, "right")) 
    {
        return;
    }

    return {
        type: "CHART.SET_DIMENSIONS",
        payload: { width, height, margin },
    };
};

/**
 * Sets the scale for this field in the Redux store
 * @param  {Array<String>} fields   The names of the fields to set the scale for
 * @param  {Function} scale         A d3.Scale function
 * @param  {Boolean} fromAxis       Has this scale been autogenerated from an axis?
 * @return {Object}                 A redux action object
 */
const setScales = (fields, scale, fromAxis) => (dispatch) => {
    // TODO log this case?
    if (!scale) return;

    dispatch({
        type: "CHART.SET_SCALES",
        payload: { fields, scale, fromAxis },
    });
};

/**
 * Sets the theme for the chart in the Redux store
 * @param  {Object} theme   The theme object
 * @return {Object}                 A redux action object
 */
const setTheme = (theme) => (dispatch) => {
    if (theme === "light") {
        dispatch({
            type: "CHART.SET_THEME",
            payload: themes.light,
        });

        return;
    }

    if (theme === "dark") {
        dispatch({
            type: "CHART.SET_THEME",
            payload: themes.dark,
        });

        return;
    }

    dispatch({
        type: "CHART.SET_THEME",
        payload: theme,
    });
};

/**
 * Sets the duration for animations in the Redux store
 * @param  {Number} duration The duration in miliseconds
 * @return {Object}          A redux action object
 */
const setAnimationDuration = (duration) => ({
    type: "CHART.SET_ANIMATION_DURATION",
    payload: duration,
});

/**
 * Sets the data for the chart in the Redux store
 * @param  {Array}  data An array of the data for the chart
 * @return {Object}      A redux action object
 */
const setData = (data = []) => {
    // TODO: Enforce arrays
    return {
        type: "CHART.SET_DATA",
        payload: data,
    };
};

const chartActions = {
    setDimensions,
    setScales,
    setData,
    setTheme,
    setAnimationDuration,
};

export { chartActions };
