import { createSelector } from "reselect";

import { PROGRESSIVE_RENDER_THRESHOLD } from "../../constants";

const EMPTY_OBJECT = {};
const EMPTY_ARRAY = [];
const EMPTY_MARGIN = { left: 0, right: 0, top: 0, bottom: 0 };

const chartSelectors = {
    /**
     * Returns the store for the chart part of state
     * @param  {Object} state The application state
     * @return {Object}       The state
     */
    store: (state) => state.chart || EMPTY_OBJECT,

    /**
     * Returns the data for the chart
     * @param  {Object} state The application state
     * @return {Object}       The chart data
     */
    data: (state) => chartSelectors.store(state).data || EMPTY_ARRAY,

    /**
     * Returns the duration to run animations for
     * @param  {Object} state The application state
     * @return {Number}       The duration in milliseconds
     */
    animationDuration: (state) => {
        const animationDuration = chartSelectors.store(state).animationDuration;
        const data = chartSelectors.data(state);

        // If we have a large dataset, then we're going to default
        // automatically to no animations
        if (data.length && data.length > PROGRESSIVE_RENDER_THRESHOLD) {
            return 0;
        }

        return animationDuration || 0;
    },

    /**
     * Represents the scales that the chart uses
     * @type {Object}
     */
    scales: {
        store: (state) => chartSelectors.store(state).scales || EMPTY_OBJECT,

        /**
         * Return a scale based on the field
         * @param  {Object} state           The application state
         * @param  {String} field           The field to get the scale of
         * @return {Function}               The d3.Scale function
         */
        getScale: (state, field) => {
            const store = chartSelectors.store(state);

            // Manually defined scales take precent
            const scales = store.scales || {};
            if (scales[field]) {
                return scales[field];
            }

            // Automatic scales generated by axis are the fallback
            const axisScales = store.axisScales || {};
            if (axisScales[field]) {
                return axisScales[field];
            }

            return undefined;
        },

        /**
         * Return a scale based on the field, preferring an Axis scale
         * @param  {Object} state           The application state
         * @param  {String} field           The field to get the scale of
         * @return {Function}               The d3.Scale function
         */
        getAxisScale: (state, field) => {
            const store = chartSelectors.store(state);

            // Axis scale takes precedent
            const axisScales = store.axisScales || {};
            if (axisScales[field]) {
                return axisScales[field];
            }

            // Manually defined scales take precent
            const scales = store.scales || {};
            if (scales[field]) {
                return scales[field];
            }

            return undefined;
        },
    },

    /**
     * Returns dimension based information for the chart
     */
    dimensions: {
        store: (state) => chartSelectors.store(state).dimensions || EMPTY_OBJECT,

        /**
         * Returns the width of the chart
         * @param  {Object} state The application state
         * @return {Number}       The width
         */
        width: (state) => chartSelectors.dimensions.store(state).width || 0,

        /**
         * Returns the height of the chart
         * @param  {Object} state The application state
         * @return {Number}       The height
         */
        height: (state) => chartSelectors.dimensions.store(state).height || 0,

        /**
         * Returns the margin of the chart
         * @param  {Object} state The application state
         * @return {Object}       The margin
         */
        margin: (state) => chartSelectors.dimensions.store(state).margin || EMPTY_MARGIN,
    },

    /**
     * Returns the theme for the chart
     * @param {Object} state The application state
     * @return {Object} The theme object
     */
    theme: (state) => chartSelectors.store(state).theme,
};

/**
 * Returns the margin of the chart
 * @param  {Object} state The application state
 * @return {Object}       The margin
 */
chartSelectors.dimensions.margin = createSelector(chartSelectors.dimensions.store, (dimensions) => {
    return dimensions?.margin || EMPTY_MARGIN;
});

export { chartSelectors };
