---
name: Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npm run lint

  audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npm audit --production --audit-level moderate

  unit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npm test

  chromatic:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Install
        run: npm ci
      - name: Chromatic
        run: npx chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
