---
name: On Push to Master

on:
  push:
    branches:
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
      - name: pnpm Install
        run: pnpm install
      - name: Lint
        run: pnpm run lint

  audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
      - name: pnpm Install
        run: pnpm install
      - name: Run Linting
        run: pnpm audit --production --audit-level moderate

  unit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
      - name: pnpm Install
        run: pnpm install
      - name: Run Unit Tests
        run: pnpm test

  changesets_version:
    runs-on: ubuntu-latest
    needs: [lint, unit]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    outputs:
      changes: ${{ steps.version.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup pnpm
        uses: IPWright83/pnpm-setup-cache-action@v5
      - name: changeset version
        id: version
        run: echo ::set-output name=changes::$(pnpm bump 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')
      - name: Update lockfile
        if: steps.version.outputs.changes == 'true'
        run: pnpm install
      - name: Create Tags
        if: steps.version.outputs.changes == 'true'
        run: pnpm changeset tag
      - name: Push changes
        if: steps.version.outputs.changes == 'true'
        run: |
          git config user.email ipwright83+dev@gmail.com
          git config user.name "Ian Wright"
          git add -A
          git commit -m "Version packages" || echo "No changes to commit"
          git push --follow-tags

  publish:
    runs-on: ubuntu-latest
    needs: changesets_version
    # This will only run if there were no changesets.
    ## the next triggered build from the push will then pass this step and continue with the release
    if: always() && needs.changesets_version.outputs.changes == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@<scope>"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: setup pnpm
        uses: IPWright83/pnpm-setup-cache-action@v5
      - name: Build
        run: pnpm run build
      - name: Release packages
        run: pnpm publish -r --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  deploy_storybook:
    needs: changesets_version
    if: "!contains(github.event.head_commit.message, 'skip storybook') && needs.changesets_version.outputs.changes == 'false'"
    runs-on: ubuntu-latest
    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - name: setup pnpm
        uses: IPWright83/pnpm-setup-cache-action@v5
      - run: pnpm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

  update_chromatic_baseline:
    needs: changesets_version
    if: "!contains(github.event.head_commit.message, 'skip chromatic') && needs.changesets_version.outputs.changes == 'false'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup pnpm
        uses: IPWright83/pnpm-setup-cache-action@v5
      - name: Chromatic
        run: npx chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes --auto-accept-changes
