---
name: Publish to NPM

on:
  push:
    branches:
      - "master"

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2.2.2
      - uses: phish108/autotag-action@1.1.51
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}

  deploy_storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2.2.2
      - name: pnpm Install
        run: pnpm install
      - run: pnpm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
      - name: pnpm Install
        run: pnpm install
      - name: Chromatic
        run: npx chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes --auto-accept-changes
